/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-29 14:23:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import usuario.*;

public final class donacion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("usuario");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String mensaje = null;

    // Form submission handling
    if (request.getMethod().equalsIgnoreCase("POST")) {
        usuario us = new usuario();
        String be = request.getParameter("be");
        String or = request.getParameter("or");
        String ds = request.getParameter("ds");
        String re = request.getParameter("re");

        HttpSession sesion = request.getSession(); 
        Integer user1 = (Integer) sesion.getAttribute("id_us");

        if (user1 != null && us.insertar_recurso(be, or, ds, re, user1)) {
            mensaje = "Recurso insertado, habla con nuestros supervisores para la donación.";
        } else {
            mensaje = "Datos incorrectos.";
        }

        // Store the message in session to display it after the redirect
        sesion.setAttribute("mensaje", mensaje);
        
        // Redirect to the same page to handle the GET request and display the message
        response.sendRedirect("donacion.jsp");
        return; // Ensure no further processing in this request
    } else {
        // Get the message from session
        HttpSession sesion = request.getSession();
        mensaje = (String) sesion.getAttribute("mensaje");
        // Remove the message from session after retrieving it
        if (mensaje != null) {
            sesion.removeAttribute("mensaje");
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Donación</title>\r\n");
      out.write("    <link href=\"estilos.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"cuerpo\">\r\n");
      out.write("    <div class=\"cuadro\">\r\n");
      out.write("        <h1 class=\"titulo\">Ayuda Alimentaria</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul class=\"menu\">\r\n");
      out.write("            <li class=\"item\"><a href=\"donacion.jsp\">Donación</a></li>\r\n");
      out.write("            <li class=\"item\"><a href=\"cerrar_sesion.jsp\">Cerrar Sesión</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"cuadro2\">\r\n");
      out.write("            <h2 class=\"titulo2\">Donación</h2>\r\n");
      out.write("            <hr> \r\n");
      out.write("            <form action=\"donacion.jsp\" method=\"post\">\r\n");
      out.write("                <label class=\"item_reg\">Beneficiario: <input type=\"text\" name=\"be\" required></label>\r\n");
      out.write("                <label class=\"item_reg\">Origen: <input type=\"text\" name=\"or\" required></label>\r\n");
      out.write("                <label class=\"item_reg\">Destino: <input type=\"text\" name=\"ds\" required></label>\r\n");
      out.write("                <label class=\"item_reg\">Recurso: <input type=\"text\" name=\"re\" required></label>\r\n");
      out.write("                <div class=\"item_login\">\r\n");
      out.write("                    <input value=\"Ingresar\" name=\"ingresar\" type=\"submit\" class=\"button\">  \r\n");
      out.write("                    <input value=\"Cancelar\" name=\"cancelar\" type=\"reset\" class=\"button\">\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 if (mensaje != null && !mensaje.isEmpty()) { 
      out.write("\r\n");
      out.write("                    <p>");
      out.print( mensaje );
      out.write("</p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer class=\"footer\"> Contactos con nosotros: telf: 3821-660 cel:098234334</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
