/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-29 14:17:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class informacion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Informacion</title>\r\n");
      out.write("<link href=\"estilos.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"cuerpo\">\r\n");
      out.write("<div class=\"cuadro\">\r\n");
      out.write("<h1 class=\"titulo\">Ayuda Alimentaria</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<nav>\r\n");
      out.write("<ul class=\"menu\">\r\n");
      out.write("<li class=\"item\"><a href=\"informacion.jsp\">Información</a></li>\r\n");
      out.write("<li class=\"item\"><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("<div class=\"contr\">\r\n");
      out.write("<img src=\"media/desnutrición.jpg\" idth=\"300\" height=\"300\" >\r\n");
      out.write("<div class=\"text\">\r\n");
      out.write("<div class=\"cuadro2\">\r\n");
      out.write("            <h2> La ayuda alimentaria no solo es un acto </h2>\r\n");
      out.write("            <h2>de generosidad, sino una poderosa </h2>\r\n");
      out.write("            <h2>manifestación de solidaridad y </h2>\r\n");
      out.write("            <h2>humanidad. En momentos de crisis,</h2> \r\n");
      out.write("            <h2>cuando el hambre y la desesperación </h2>\r\n");
      out.write("            <h2>golpean a las comunidades más </h2>\r\n");
      out.write("            <h2>vulnerables, cada esfuerzo cuenta.</h2></div>\r\n");
      out.write("            </div>\r\n");
      out.write("<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/s7i-zFgLgnU\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("<div class=\"contr\">\r\n");
      out.write("<img src=\"media/images.jpg\" idth=\"300\" height=\"300\" >\r\n");
      out.write("<div class=\"text\">\r\n");
      out.write("<div class=\"cuadro2\">\r\n");
      out.write("            <h2> La ayuda alimentaria es una luz en la </h2>\r\n");
      out.write("            <h2>oscuridad, un recordatorio de que, en los </h2>\r\n");
      out.write("            <h2>tiempos más difíciles, no estamos solos. </h2>\r\n");
      out.write("            <h2>Ayudemos a las personas que mas necesitan  </h2>\r\n");
      out.write("            <h2>apoya a la causa, seamos mejores </h2></div>\r\n");
      out.write("            </div>\r\n");
      out.write("<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/9Qv00KqFwyc\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"footer\"> <p>Contactos con nosotros: telf: 3821-660 cel:098234334  Más link aqui:</p>\r\n");
      out.write("<a href=\"https://www.youtube.com/watch?v=oOn_rTintBk\">Comida para todos</a>\r\n");
      out.write("<a href=\"https://www.youtube.com/watch?v=dqzY3mJqEFc&t=1s\">CRISIS Alimentaria</a></footer>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
